### PR TITLE
Remove Bootstrap dependency

### LINKED ISSUE #16: Remove hard dependency on Bootstrap 5
The [hard dependency on Bootstrap 5](https://github.com/geneontology/wc-gocam-viz/blob/fad45dd261091c27dce8953fa5da062214bd5f17/package.json#L29) makes this challenging to integrate the widget into downstream projects. Some scenarios:

1. Host application doesn't use Bootstrap at all. Once the widget is loaded, Bootstrap styles are injected. Even though the host application doesn't use any Bootstrap CSS classes its [global styling](https://getbootstrap.com/docs/5.3/getting-started/introduction/#important-globals) could alter the appearance of the host application.
2. Host application uses an older version of the Bootstrap. This is the case with AmiGO and the Alliance site, which both use Bootstrap 4. Once the widget is loaded the existing Bootstrap 4 style definitions are overridden with Bootstrap 5 definitions. This has all sorts of unpredictable side effects. For example, before loading the widget:

Image

And after:

Image

3. Host application also uses Bootstrap 5. This is the best case scenario because there won't be any style conflicts. But in this case the application still ends up with two copies of Bootstrap 5, increasing the size of the host application bundle.

At the very least it seems like Bootstrap should be a peer dependency. This would fix the third scenario, but not the first two. To help the first two scenarios I'd suggest seeing if:

* Bootstrap could be a peer dependency _and_ the requirement relaxed to be something like `>=4.x`
* Bootstrap could be dropped altogether. Could a few custom CSS classes suffice instead?

### PR DESCRIPTION
**Pull request by pkalita-lbl**
Fixes #16 

## Summary of changes

* Bootstrap dependency is removed and any necessary style definitions have been added/updated in our own stylesheets. In particular Bootstrap's `card` component was used somewhat extensively. This has been replaced by a `panel` (and related) class defined in `src/scss/_panel.scss`. 
* A new `go-loading-spinner` component has been added. This was previously defined within the `wc-gocam-viz` component, but it seemed cleaner to extract it into a standalone component. 
* All components now use the shadow DOM.
* Various CSS classes with no existing style rules have been removed from elements.
* Fixed a bug in the `wc-gocam-panel` component where updating the `repository` didn't actually refetch the GOCAM data -- not strictly related to any of the other changes but it made testing easier.

## Caveats

* These changes aren't pixel-level identical with the latest released version. I did my best to imitate the existing style, but I did make some simplifications here and there where I felt it made sense. Compare:
wc-gocam-viz-bootstrap

* I did not make an attempt to harmonize the CSS class names representing all the parts of each component. I see that as part of the work of #17. 
* The `wc-gocam-viz` component previously used the Bootstrap `container` class at the top-level which limited how wide the component could be. I see this as the responsibility of the hosting page to determine, not the component itself. So now the component will be as wide as whatever container the user puts it in.

### CODE REVIEW

**Comment by kltm** [comment]
Part of https://github.com/geneontology/wc-gocam-viz/issues/16 ?
Looks good to me; will defer to @tmushayahama to look at and merge.

**Comment by pkalita-lbl** [comment]
Oops, yes. Will update the description.

**Comment by kltm** [comment]
Sorry, didn't mean to nudge, just fiddling with the paperclips.

**Comment by tmushayahama** [comment]
@pkalita-lbl @kltm This looks really great, far more superior and cleaner than the previous. Thanks

Maybe a tiny thing, but lets merge it first. we should prefix all ex-bootstrap name clashes items with "gocam-" like .panel, .panel-header in case our host has bootstrap

one more test, I couldn't tell if it was there in the previous is the indentation of the nested nodes i.e

_part of_ A
--_part of_ B

**Comment by tmushayahama** [comment]
@pkalita-lbl @kltm. Just to add tested on a much model and good

image

**Comment by kltm** [comment]
@tmushayahama Cheers!

**Pull request merged**
